//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UzsakymuUzduotis
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int idProduct { get; set; }
        public string productTitle { get; set; }
        public double productPrice { get; set; }
    }
}
